[phases.setup]
nixPkgs = ['nodejs_20', 'npm-9_x', 'openssl']

[phases.install]
cmds = [
  'npm install -g pnpm',
  'set -e && BUILD_ROOT="" && echo "Checking for repository root..." && if [ -f /app/pnpm-workspace.yaml ]; then BUILD_ROOT="/app"; echo "Found repo root at /app (build context is repo root)"; elif [ -f /app/../pnpm-workspace.yaml ]; then BUILD_ROOT="/app/.."; echo "Found repo root at /app/.."; elif [ -f /app/../../pnpm-workspace.yaml ]; then BUILD_ROOT="/app/../.."; echo "Found repo root at /app/../.."; elif [ -f /app/examples/nestjs/../../pnpm-workspace.yaml ]; then BUILD_ROOT="/app/examples/nestjs/../.."; echo "Found repo root at /app/examples/nestjs/../.."; else echo "ERROR: Cannot find pnpm-workspace.yaml"; echo "Current directory: $(pwd)"; echo "Contents of /app: $(ls -la /app 2>/dev/null | head -10)"; echo ""; echo "COOLIFY CONFIGURATION REQUIRED:"; echo "Set Build Context to repository root (/) not examples/nestjs"; echo "See DEPLOYMENT.md for instructions"; exit 1; fi && if [ ! -f "$BUILD_ROOT/package.json" ]; then echo "ERROR: Missing package.json in $BUILD_ROOT"; exit 1; fi && echo "Installing from $BUILD_ROOT..." && cd "$BUILD_ROOT" && npx pnpm install',
]

[phases.build]
cmds = [
  'set -e && ROOT_DIR="" && if [ -f /app/pnpm-workspace.yaml ]; then ROOT_DIR="/app"; elif [ -f /app/../pnpm-workspace.yaml ]; then ROOT_DIR="/app/.."; elif [ -f /app/../../pnpm-workspace.yaml ]; then ROOT_DIR="/app/../.."; elif [ -f /app/examples/nestjs/../../pnpm-workspace.yaml ]; then ROOT_DIR="/app/examples/nestjs/../.."; else echo "ERROR: Cannot find repository root for build"; exit 1; fi && echo "Building from $ROOT_DIR..." && cd "$ROOT_DIR" && npx pnpm build && echo "Building NestJS app..." && cd examples/nestjs && npx pnpm build && echo "Build complete"',
]

[start]
cmd = "node dist/main.js"
