[phases.setup]
nixPkgs = ['nodejs_22', 'pnpm', 'openssl']

[phases.install]
cmds = ['pnpm install']

[build]
# Build parent package first, then NestJS app
command = "pnpm run prebuild && pnpm run build"

[start]
command = "node dist/main"
