[phases.setup]
nixPkgs = ['nodejs_20', 'npm-9_x', 'openssl']

[phases.install]
cmds = [
  'npm install -g pnpm',
  'set -e',
  'echo "Finding repository root..."',
  'BUILD_ROOT=""',
  'if [ -f /app/../../package.json ] && [ -f /app/../../pnpm-workspace.yaml ]; then',
  '  BUILD_ROOT="/app/../.."',
  '  echo "Found repo root at $BUILD_ROOT (relative path)"',
  'elif [ -f /app/../package.json ] && [ -f /app/../pnpm-workspace.yaml ]; then',
  '  BUILD_ROOT="/app/.."',
  '  echo "Found repo root at $BUILD_ROOT (relative path)"',
  'else',
  '  echo "Searching for repository in /artifacts..."',
  '  WORKSPACE_FILE=$(find /artifacts -name "pnpm-workspace.yaml" -type f 2>/dev/null | head -1)',
  '  if [ -n "$WORKSPACE_FILE" ]; then',
  '    BUILD_ROOT=$(dirname "$WORKSPACE_FILE")',
  '    echo "Found repo root at $BUILD_ROOT (from artifacts)"',
  '  else',
  '    echo "ERROR: Cannot find repository root with pnpm-workspace.yaml"',
  '    echo "Searched in /artifacts and relative paths from /app"',
  '    echo "Configure Coolify to use repository root as build context"',
  '    exit 1',
  '  fi',
  'fi',
  'if [ ! -f "$BUILD_ROOT/package.json" ]; then',
  '  echo "ERROR: Found directory $BUILD_ROOT but missing package.json"',
  '  exit 1',
  'fi',
  'echo "Installing dependencies from $BUILD_ROOT..."',
  'cd "$BUILD_ROOT"',
  'npx pnpm install',
]

[phases.build]
cmds = [
  'set -e',
  'echo "Finding repository root for build..."',
  'ROOT_DIR=""',
  'if [ -f /app/../../package.json ] && [ -f /app/../../pnpm-workspace.yaml ]; then',
  '  ROOT_DIR="/app/../.."',
  '  echo "Found repo root at $ROOT_DIR (relative path)"',
  'elif [ -f /app/../package.json ] && [ -f /app/../pnpm-workspace.yaml ]; then',
  '  ROOT_DIR="/app/.."',
  '  echo "Found repo root at $ROOT_DIR (relative path)"',
  'else',
  '  echo "Searching for repository in /artifacts..."',
  '  WORKSPACE_FILE=$(find /artifacts -name "pnpm-workspace.yaml" -type f 2>/dev/null | head -1)',
  '  if [ -n "$WORKSPACE_FILE" ]; then',
  '    ROOT_DIR=$(dirname "$WORKSPACE_FILE")',
  '    echo "Found repo root at $ROOT_DIR (from artifacts)"',
  '  else',
  '    echo "ERROR: Cannot find repository root for build"',
  '    echo "Searched in /artifacts and relative paths from /app"',
  '    exit 1',
  '  fi',
  'fi',
  'if [ ! -f "$ROOT_DIR/package.json" ]; then',
  '  echo "ERROR: Found directory $ROOT_DIR but missing package.json"',
  '  exit 1',
  'fi',
  'echo "Building root package from $ROOT_DIR..."',
  'cd "$ROOT_DIR"',
  'npx pnpm build',
  'echo "Building NestJS app..."',
  'cd examples/nestjs',
  'npx pnpm build',
  'echo "Build complete. Output in dist/"',
]

[start]
cmd = "node dist/main.js"
